language: haskell
ghc: 7.8
sudo: required

before_install:
  - chmod +x ./generator

before_script:
  - sudo apt-get update
  - sudo apt-get install libc6:i386 libstdc++6:i386

script:
  - ./generator 5
  - cabal configure --enable-tests && cabal build && cabal test
